export interface LearnResource {
  type: "Paper" | "GitHub" | "Reading List";
  title: string;
  source: string;
  date: string;
  href: string;
  summary: string;
  tags: string[];
}

export interface LearnTopic {
  slug: string;
  title: string;
  subtitle: string;
  description: string;
  resources: LearnResource[];
}

export const lastUpdated = "2026-06-30";

export const learnTopics: LearnTopic[] = [
  {
    slug: "mathematics",
    title: "Mathematics",
    subtitle: "Probability, dynamics, optimization, and mathematical foundations",
    description:
      "Papers and repositories that connect rigorous mathematical ideas with modeling, simulation, and computational tools.",
    resources: [
      {
        type: "Paper",
        title: "McMg: A Learned Phase-Space Multi-channel Multigrid Preconditioner for Helmholtz Equation",
        source: "arXiv",
        date: "2026-06-29",
        href: "https://arxiv.org/abs/2606.30495",
        summary:
          "A learned multigrid preconditioner that preserves phase and direction information for difficult high-frequency Helmholtz solves.",
        tags: ["Numerical Analysis", "PDE Solvers", "Scientific ML"],
      },
      {
        type: "Paper",
        title: "Peelings and Wrappings of Families of Convex Sets with Applications to Strongly Convex Sets Generated by Random Samples",
        source: "arXiv",
        date: "2026-06-29",
        href: "https://arxiv.org/abs/2606.30617",
        summary:
          "Develops geometric peeling and wrapping operations for convex-set families, then applies them to probabilistic limits for random convex hulls.",
        tags: ["Probability", "Convex Geometry", "Random Sets"],
      },
      {
        type: "Paper",
        title: "Second-Order KKT Guarantees for Bregman ADMM in Nonconvex and Non-Lipschitz Optimization",
        source: "arXiv",
        date: "2026-06-26",
        href: "https://arxiv.org/abs/2606.28307",
        summary:
          "Extends ADMM analysis beyond standard Lipschitz-gradient assumptions, useful for connecting optimization theory with practical nonconvex algorithms.",
        tags: ["Optimization", "ADMM", "Nonconvex Analysis"],
      },
      {
        type: "Paper",
        title: "Automated Galerkin time stepping in Irksome",
        source: "arXiv",
        date: "2026-06-25",
        href: "https://arxiv.org/abs/2606.27300",
        summary:
          "Automates discontinuous and continuous Galerkin-in-time discretizations, making structure-preserving time stepping easier to experiment with.",
        tags: ["Numerical Analysis", "Galerkin Methods", "Scientific Computing"],
      },
      {
        type: "GitHub",
        title: "stdlib-js/stdlib",
        source: "GitHub",
        date: "Updated 2026-06-30",
        href: "https://github.com/stdlib-js/stdlib",
        summary:
          "A broad numerical computing library for JavaScript and TypeScript, useful as a practical computational reference.",
        tags: ["Numerical Computing", "Library", "TypeScript"],
      },
      {
        type: "GitHub",
        title: "quantified-uncertainty/squiggle",
        source: "GitHub",
        date: "Updated 2026-06-27",
        href: "https://github.com/quantified-uncertainty/squiggle",
        summary:
          "A probability-focused modeling language and hub for representing uncertainty in forecasts and decision models.",
        tags: ["Probability", "Uncertainty", "Forecasting"],
      },
    ],
  },
  {
    slug: "machine-learning",
    title: "Machine Learning",
    subtitle: "Deep learning, evaluation, optimization, and applied ML systems",
    description:
      "A running list of ML papers and codebases I am reading to improve model-building, evaluation, and deployment intuition.",
    resources: [
      {
        type: "Paper",
        title: "One-Step Gradient Delay is Not a Barrier for Large-Scale Asynchronous Pipeline Parallel LLM Pretraining",
        source: "arXiv",
        date: "2026-06-29",
        href: "https://arxiv.org/abs/2606.30634",
        summary:
          "Shows that optimizer choice and error-feedback corrections can make asynchronous pipeline-parallel LLM pretraining robust to one-step gradient delay.",
        tags: ["LLM Training", "Pipeline Parallelism", "Optimization"],
      },
      {
        type: "Paper",
        title: "Pessimism's Paradox: Conservative Offline Training Amplifies Reward Hacking During Online Adaptation in Reasoning Models",
        source: "arXiv",
        date: "2026-06-29",
        href: "https://arxiv.org/abs/2606.30627",
        summary:
          "A useful cautionary result: more conservative DPO checkpoints can become more vulnerable to reward hacking during online adaptation.",
        tags: ["Alignment", "Reward Hacking", "Reasoning Models"],
      },
      {
        type: "Paper",
        title: "VGB for Masked Diffusion Model: Efficient Test-time Scaling for Reward Satisfaction and Sample Editing",
        source: "arXiv",
        date: "2026-06-26",
        href: "https://arxiv.org/abs/2606.28301",
        summary:
          "Introduces value-guided branching for masked diffusion, a clean example of test-time scaling for constrained generation and editing.",
        tags: ["Diffusion Models", "Test-Time Scaling", "Generative ML"],
      },
      {
        type: "Paper",
        title: "Reinforcement Learning without Ground-Truth Solutions can Improve LLMs",
        source: "arXiv",
        date: "2026-06-25",
        href: "https://arxiv.org/abs/2606.27369",
        summary:
          "Explores rank-based reinforcement learning for LLMs when ground-truth solutions are unavailable, expanding where RL-style post-training can be applied.",
        tags: ["LLMs", "Reinforcement Learning", "Post-Training"],
      },
      {
        type: "GitHub",
        title: "vllm-project/vllm",
        source: "GitHub",
        date: "Updated 2026-06-30",
        href: "https://github.com/vllm-project/vllm",
        summary:
          "A high-throughput LLM inference and serving engine that is central to practical deployment and systems-level ML work.",
        tags: ["LLM Serving", "Inference", "PyTorch"],
      },
      {
        type: "GitHub",
        title: "huggingface/transformers",
        source: "GitHub",
        date: "Updated 2026-06-30",
        href: "https://github.com/huggingface/transformers",
        summary:
          "The standard model-definition and tooling library for modern ML systems across text, vision, audio, and multimodal models.",
        tags: ["Transformers", "Model Library", "PyTorch"],
      },
    ],
  },
  {
    slug: "ai-agents",
    title: "AI Agents",
    subtitle: "Tool use, memory, autonomy, benchmarks, and agent infrastructure",
    description:
      "Resources for understanding how AI agents plan, use tools, evaluate themselves, and operate as long-running systems.",
    resources: [
      {
        type: "Paper",
        title: "Self-Evolving World Models for LLM Agent Planning",
        source: "arXiv",
        date: "2026-06-29",
        href: "https://arxiv.org/abs/2606.30639",
        summary:
          "Introduces WorldEvolver, which improves agent planning by revising episodic and semantic memory at test time while keeping model weights frozen.",
        tags: ["World Models", "Agent Planning", "Memory"],
      },
      {
        type: "Paper",
        title: "Entity Binding Failures in Tool-Augmented Agents",
        source: "arXiv",
        date: "2026-06-29",
        href: "https://arxiv.org/abs/2606.30531",
        summary:
          "Separates tool correctness from entity correctness and shows why agents need explicit binding, clarification, and provenance before taking actions.",
        tags: ["Tool Use", "Agent Safety", "Entity Resolution"],
      },
      {
        type: "GitHub",
        title: "omnigent-ai/omnigent",
        source: "GitHub",
        date: "Updated 2026-06-29",
        href: "https://github.com/omnigent-ai/omnigent",
        summary:
          "A meta-harness for orchestrating coding and research agents while swapping harnesses, enforcing policies, and sandboxing execution.",
        tags: ["Agent Framework", "Orchestration", "Sandboxing"],
      },
      {
        type: "Paper",
        title: "VIGIL: Runtime Enforcement of Behavioral Specifications in AI Agent Skills",
        source: "arXiv",
        date: "2026-06-25",
        href: "https://arxiv.org/abs/2606.26524",
        summary:
          "Targets a practical safety layer for agent skills by turning behavioral specifications into runtime enforcement rather than passive documentation.",
        tags: ["Agent Safety", "Skills", "Runtime Enforcement"],
      },
      {
        type: "GitHub",
        title: "caura-ai/caura-memclaw",
        source: "GitHub",
        date: "Updated 2026-06-28",
        href: "https://github.com/caura-ai/caura-memclaw",
        summary:
          "A governed shared-memory layer for agent fleets with MCP-native access, trust tiers, audit trails, and retrieval policies.",
        tags: ["Agent Memory", "MCP", "Governance"],
      },
      {
        type: "GitHub",
        title: "IBM/AssetOpsBench",
        source: "GitHub",
        date: "Updated 2026-06-28",
        href: "https://github.com/IBM/AssetOpsBench",
        summary:
          "A domain-specific benchmark and framework for evaluating multi-agent industrial operations workflows across hundreds of scenarios.",
        tags: ["Agent Benchmarks", "Multi-Agent", "Operations"],
      },
    ],
  },
];
